includes:
  - https://github.ibm.com/cloud-docs/fortigate-10g
  - https://github.ibm.com/cloud-docs/cloud-infrastructure
  - https://github.ibm.com/cloud-docs-solutions/solution-tutorials
  - https://github.ibm.com/cloud-docs/virtual-router-appliance
  - https://github.ibm.com/cloud-docs/vsrx
translation:
  exclude:
    byFilePath:
      - file-dont-translate.md
      - folder-dont-translate/
